import"./assets/modulepreload-polyfill-B5Qt9EMX.js";/* empty css                      */import{S as l}from"./assets/vendor-CgTBfC_f.js";const e=document.querySelector(".gallery");if(!e)console.warn("Gallery root not found on this page");else{const a=[{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-1-MTgI1q5C.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-1-large-f7ep2PYM.jpg",import.meta.url).href,description:"Team planning interface"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-2-BlBqK8bZ.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-2-large-BGrZjlDy.jpg",import.meta.url).href,description:"Light bulb and plant on table"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-3-Bk7R-ELc.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-3-large-DrnJQX06.jpg",import.meta.url).href,description:"Phone with design notes"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-4-BovugKEg.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-4-large-BideeGUT.jpg",import.meta.url).href,description:"Modern office interior"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-5-BvYm_kHs.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-5-large-CdFCxlw0.jpg",import.meta.url).href,description:"Colorful office space"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-6-B0jKZEiH.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-6-large-DqmYUguY.jpg",import.meta.url).href,description:"Open workspace with people"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-7-CPISfplD.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-7-large-CM0wPVGA.jpg",import.meta.url).href,description:"Coffee and laptop on desk"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-8-DosLElyQ.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-8-large-NRavB6m_.jpg",import.meta.url).href,description:"Person in yellow sweater"},{preview:new URL("/goit-advancedjs-hw-01/assets/gallery-9-BuZRITF2.jpg",import.meta.url).href,original:new URL("/goit-advancedjs-hw-01/assets/gallery-9-large-DD1n2IEU.jpg",import.meta.url).href,description:"Team presentation in office"}].map(({preview:r,original:t,description:i})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img
            class="gallery-image"
            src="${r}"
            alt="${i}"
          />
        </a>
      </li>
    `).join("");e.innerHTML=a,new l(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250})}
//# sourceMappingURL=1-gallery.js.map
